In [3]:
from sklearn import datasets
import random
import numpy as np
iris=datasets.load_iris()
data=iris.data
len(data)

150

In [5]:
# Sample 30 points randomly from 150 ponits
n=len(data)
m=30
p=m/n

# p=30/150 

sample_data=[]
for i in range(0,n):
    if random.random() <= p:
        sample_data.append(data[i,:])
len(sample_data)

33

In [6]:
sample_data

[array([4.7, 3.2, 1.3, 0.2]),
 array([5. , 3.6, 1.4, 0.2]),
 array([4.4, 2.9, 1.4, 0.2]),
 array([5.4, 3.7, 1.5, 0.2]),
 array([4.8, 3.4, 1.6, 0.2]),
 array([5.1, 3.5, 1.4, 0.3]),
 array([5. , 3.4, 1.6, 0.4]),
 array([5.2, 3.5, 1.5, 0.2]),
 array([4.7, 3.2, 1.6, 0.2]),
 array([5.4, 3.4, 1.5, 0.4]),
 array([4.9, 3.6, 1.4, 0.1]),
 array([4.4, 3. , 1.3, 0.2]),
 array([4.5, 2.3, 1.3, 0.3]),
 array([5.1, 3.8, 1.9, 0.4]),
 array([4.8, 3. , 1.4, 0.3]),
 array([5.3, 3.7, 1.5, 0.2]),
 array([6.9, 3.1, 4.9, 1.5]),
 array([6.5, 2.8, 4.6, 1.5]),
 array([5.9, 3. , 4.2, 1.5]),
 array([6.1, 3. , 4.6, 1.4]),
 array([5. , 2.3, 3.3, 1. ]),
 array([5.8, 2.7, 5.1, 1.9]),
 array([6.5, 3. , 5.8, 2.2]),
 array([7.3, 2.9, 6.3, 1.8]),
 array([6.4, 2.7, 5.3, 1.9]),
 array([6.8, 3. , 5.5, 2.1]),
 array([5.7, 2.5, 5. , 2. ]),
 array([6. , 2.2, 5. , 1.5]),
 array([7.2, 3.2, 6. , 1.8]),
 array([7.4, 2.8, 6.1, 1.9]),
 array([6.4, 2.8, 5.6, 2.2]),
 array([6.8, 3.2, 5.9, 2.3]),
 array([6.5, 3. , 5.2, 2. ])]